DDPM:
  timesteps: 1000
  loss_type: 'l1'
  image_size: 32
  in_channels: 3
  model_channels: 64
  out_channels: 3
  num_res_blocks: 2
  attn_resolutions: [32, 16, 8]

Conditioning_Model:
  z_dim: 128
  checkpoint_name: 'encoder_stage2'
  model_name: 'Stage2_AE_DTDB_Date-2023-2-19-20-20-13_my//'
  model_path: './ckpt/DTDB/clouds/'

First_stage_model:
  checkpoint_encoder: 'best_PFVD_ENC'
  checkpoint_decoder: 'best_PFVD_GEN'
  model_name: 'Stage1_DTDB_Date-2023-2-15-3-12-42_my//'
  model_path: './ckpt/DTDB/clouds/'

Training:
  n_epochs: 101
  lr: 1e-4
  workers: 12
  bs: 12
  bs_eval: 10
  verbose_idx: 30
  weight_decay: 0
  gamma: 0.5
  step_size: 6
  beta1: 0.9
  beta2: 0.99
  amsgrad: True
  savename: 'my3'
  save_path: './ckpt/DTDB/clouds/'

Data:
  sequence_length: 17
  img_size: 128
  dataset: 'DTDB'
  texture: 'clouds'
  image_format: 'png'
  aug: True
  iter_train: 50
  iter_eval: 5
  iter_test: 5
  data_path: './data/DTDB/dynamic_textures/'
  Augmentation:
    brightness: 0.3
    contrast: 0.3
    saturation: 0.3
    hue: 0.15
    prob_hflip: 0.5

Logging:
  entity: 'diffusion'
  project: "i2v"
  mode: 'online'