Flow:
  n_flows: 20
  flow_hidden_depth: 2
  flow_mid_channels_factor: 8

Conditioning_Model:
  z_dim: 128
  checkpoint_name: 'encoder_stage2'
  model_name: 'Stage2_AE_DTDB_Date-2023-1-12-1-42-29_1/'
  model_path: './ckpt/DTDB/clouds/'

First_stage_model:
  checkpoint_encoder: 'best_PFVD_ENC'
  checkpoint_decoder: 'best_PFVD_GEN'
  model_name: 'Stage1_DTDB_Date-2023-1-4-7-34-44_1/'
  model_path: './ckpt/DTDB/clouds/'

Training:
  n_epochs: 31
  lr: 1e-5
  workers: 12
  bs: 50
  bs_eval: 10
  verbose_idx: 30
  weight_decay: 0
  gamma: 0.5
  step_size: 6
  beta1: 0.9
  beta2: 0.99
  amsgrad: True
  savename: '1'
  save_path: './ckpt/DTDB/clouds/'

Data:
  sequence_length: 17
  img_size: 128
  dataset: 'DTDB'
  texture: 'clouds'
  image_format: 'png'
  aug: True
  iter_train: 50
  iter_eval: 5
  iter_test: 5
  data_path: './data/DTDB/dynamic_textures/'
  Augmentation:
    brightness: 0.3
    contrast: 0.3
    saturation: 0.3
    hue: 0.15
    prob_hflip: 0.5

Logging:
  entity: 'INSERT_WANDB_NAME'
  project: "i2v"
  mode: 'online'